# Generated by Django 4.2.4 on 2023-08-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_enrollment_course_enrollments_and_more'),
        ('accounts', '0006_alter_user_id_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(through='courses.Enrollment', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
