# Generated by Django 4.2.4 on 2023-08-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_courses_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', editable=False),
        ),
        migrations.RunSQL("ALTER SEQUENCE courses_enrollment_id_seq RESTART WITH 1000;"),
    ]
