# Generated by Django 4.2.4 on 2023-09-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0016_access_access_unique_access"),
        ("accounts", "0008_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="materials",
            field=models.ManyToManyField(
                through="courses.Access", to="courses.material"
            ),
        ),
    ]
