# Generated by Django 4.2.4 on 2023-09-04 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="appraisal_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="appraisal_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="appraisal_stars",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="course_assessment_progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="course_instructional_progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="last_module",
            field=models.IntegerField(default=0),
        ),
    ]
