# Generated by Django 4.2.4 on 2023-09-04 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0002_enrollment_appraisal_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="comments",
            field=models.ManyToManyField(
                through="social.Comment", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
