# Generated by Django 4.2.4 on 2023-08-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_module_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='extra',
            new_name='is_extra',
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('order', 'course_id'), name='unique_order_course'),
        ),
    ]
