# Generated by Django 4.2.4 on 2023-09-08 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_module_module_assessment_materials_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="parent_module_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.module",
            ),
        ),
    ]
