# Generated by Django 4.2.4 on 2023-08-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_extra_material_is_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='alias',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('order', 'module_id'), name='unique_order_module'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('name', 'course_id'), name='unique_name_course'),
        ),
    ]
