# Generated by Django 4.2.4 on 2023-09-10 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_module_parent_module_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_instructional_progress', models.IntegerField(default=0)),
                ('module_assessment_progress', models.IntegerField(default=0)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='module_progress',
            constraint=models.UniqueConstraint(fields=('user_id', 'module_id'), name='unique_user_module'),
        ),
    ]
