# Generated by Django 4.2.4 on 2023-09-30 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0005_module_progress_module_progress_unique_user_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructor_type", models.CharField(max_length=1)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="instructor",
            constraint=models.UniqueConstraint(
                fields=("user_id", "course_id"), name="unique_instructor"
            ),
        ),
        migrations.AddConstraint(
            model_name="instructor",
            constraint=models.CheckConstraint(
                check=models.Q(("instructor_type__in", ["E", "T", "A"])),
                name="valid_type_of_instructor",
            ),
        ),
    ]
