# Generated by Django 4.2.4 on 2023-10-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_alter_access_last_view_alter_access_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
