# Generated by Django 4.2.4 on 2023-10-30 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_alter_access_last_view_alter_access_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField(max_length=1000)),
                ("pages", models.PositiveIntegerField(default=1)),
                (
                    "material_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.material",
                    ),
                ),
            ],
        ),
    ]
