# Generated by Django 4.2.4 on 2023-08-31 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_alter_materialhtml_material_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialhtml",
            name="material_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="courses.material"
            ),
        ),
    ]
