# Generated by Django 4.2.4 on 2023-09-01 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_materialvideo"),
        ("courses", "0014_alter_materialhtml_material_id"),
    ]

    operations = []
