# Generated by Django 4.2.4 on 2023-09-01 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_merge_20230901_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='appraisals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='average_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='course_assessment_materials',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='course_extra_materials',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='course_instructional_materials',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='min_assessment_progress',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='course',
            name='parent_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
