# Generated by Django 4.2.4 on 2023-09-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0016_access_access_unique_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="material",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="material",
            name="total_comments",
            field=models.IntegerField(default=0),
        ),
    ]
