# Generated by Django 4.2.4 on 2023-09-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0017_material_dislikes_material_likes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="last_view",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
