# Generated by Django 4.2.4 on 2023-09-06 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialIoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_time", models.IntegerField()),
                ("max_memory", models.IntegerField()),
                ("isActive", models.BooleanField(default=True)),
                (
                    "material_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.material",
                    ),
                ),
            ],
        ),
    ]
