# Generated by Django 4.2.4 on 2023-09-09 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_time', models.IntegerField()),
                ('max_memory', models.IntegerField()),
                ('material_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.material')),
            ],
        ),
        migrations.CreateModel(
            name='IoCodeSubmission',
            fields=[
                ('submission_id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now=True)),
                ('response_char', models.CharField(max_length=1)),
                ('execution_time', models.IntegerField()),
                ('execution_memory', models.IntegerField()),
                ('completion_rate', models.FloatField()),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.material')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='iocodesubmission',
            constraint=models.CheckConstraint(check=models.Q(('response_char__in', {'E', 'A', 'C', 'W', 'T'})), name='char_check'),
        ),
    ]
