# Generated by Django 4.2.4 on 2023-09-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialiocode',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
