# Generated by Django 4.2.4 on 2023-10-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ioc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iocodesubmission",
            name="code",
            field=models.CharField(default='print("hola mundo")'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="iocodesubmission",
            name="language",
            field=models.CharField(default="py3", max_length=10),
            preserve_default=False,
        ),
    ]
