# Generated by Django 4.2.4 on 2023-09-07 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ioc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IoCodeSubmission",
            fields=[
                (
                    "submission_id",
                    models.BigAutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_date", models.DateTimeField(auto_now=True)),
                ("response_char", models.CharField(max_length=1)),
                ("execution_time", models.IntegerField()),
                ("execution_memory", models.IntegerField()),
                ("completion_rate", models.FloatField()),
                (
                    "material_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.material",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="iocodesubmission",
            constraint=models.CheckConstraint(
                check=models.Q(("response_char__in", {"T", "W", "E", "A", "C"})),
                name="char_check",
            ),
        ),
    ]
