# Generated by Django 4.2.4 on 2023-09-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ioc', '0002_materialiocode_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialiocode',
            name='isActive',
        ),
    ]
