# Generated by Django 4.2.4 on 2023-10-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ioc", "0002_remove_iocodesubmission_char_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iocodesubmission",
            name="completion_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="iocodesubmission",
            name="execution_memory",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="iocodesubmission",
            name="execution_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
