# Generated by Django 4.2.4 on 2023-10-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ioc", "0003_alter_iocodesubmission_completion_rate_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="iocodesubmission",
            name="char_check",
        ),
        migrations.AddConstraint(
            model_name="iocodesubmission",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "response_char__in",
                        {"C", "A", "R", "O", "E", "W", "I", "M", "T"},
                    ),
                    ("response_char__isnull", True),
                    _connector="OR",
                ),
                name="char_check",
            ),
        ),
    ]
