# Generated by Django 4.2.4 on 2023-10-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc', '0005_materialiocode_max_points_materialiocode_min_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iocodesubmissionsummary',
            name='min_execution_time',
            field=models.FloatField(),
        ),
    ]
