# Generated by Django 4.2.4 on 2023-10-30 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ioc", "0004_1_remove_iocodesubmission_char_check_and_more"),
        ("ioc", "0006_alter_iocodesubmissionsummary_min_execution_time"),
    ]

    operations = []
