# Generated by Django 4.2.4 on 2023-09-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
