# Generated by Django 4.2.4 on 2023-09-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alias', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
